### ISSUE TITLE
Docker plugin not found on installpull access denied for flaviostutz/cepher, repository does not exist or may require 'docker login'

### ISSUE THREAD

**Issue by relipe** [flaviostutz/cepher#4]
~/cepher# docker plugin install flaviostutz/cepher \
>   --grant-all-permissions \
>   --alias=cepher \
>   MONITOR_HOSTS="${HOST_IP}:16789,${HOST_IP}:26789,${HOST_IP}:16789" \
>   ETCD_URL="http://${HOST_IP}:12379" \
>   DEFAULT_IMAGE_SIZE=100 \
>   ENABLE_AUTO_CREATE_VOLUMES=true
Error response from daemon: pull access denied for flaviostutz/cepher, repository does not exist or may require 'docker login'

**Comment by flaviostutz** [comment]
@relipe, is this still hapenning?

**Comment by relipe** [comment]
No, now it's working properly.
